# run cargo install mdbook mdbook-toc mdbook-linkcheck

[book]
authors = ["Cliff Brake"]
language = "en"
multilingual = false
src = "."
title = "Simple IoT"

[preprocessor.toc]

[output.html]
git-repository-url = "https://github.com/simpleiot/simpleiot"
edit-url-template = "https://github.com/simpleiot/simpleiot/edit/master/{path}"

[output.linkcheck]
#follow-web-links = true
